### ISSUE TITLE
ValueError: axes don't match array`

### ISSUE THREAD

**Issue by dr-askar** [rodrigo2019/keras-yolo2#5]
i have problem in load model trained using backend mobilenet 
i think it is a bug 
can any one help me to fix it 
`2019-04-01 18:06:56.158333: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2300000000 Hz
2019-04-01 18:06:56.158622: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x1cb91e0 executing computations on platform Host. Devices:
2019-04-01 18:06:56.158749: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-04-01 18:06:56.258049: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-04-01 18:06:56.258626: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x1cb8c60 executing computations on platform CUDA. Devices:
2019-04-01 18:06:56.258687: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): Tesla K80, Compute Capability 3.7
2019-04-01 18:06:56.259138: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:04.0
totalMemory: 11.17GiB freeMemory: 11.10GiB
2019-04-01 18:06:56.259200: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-04-01 18:06:56.675594: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-04-01 18:06:56.675692: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-04-01 18:06:56.675728: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-04-01 18:06:56.676051: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10754 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3.7)
100% 126/126 [00:00<00:00, 7283.08it/s]
Seen labels:	 {'as_curve': 126, 'thick': 126, 'pe': 126, 'ae': 126}
Given labels:	 ['as_curve']
Overlap labels:	 {'as_curve'}
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Loading pretrained weights: ./backend_weights/mobilenet_backend.h5
Unable to load backend weights. Using a fresh model
(13, 13)
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         (None, 416, 416, 3)       0         
_________________________________________________________________
MobileNet_backend (Model)    (None, 13, 13, 1024)      3228864   
_________________________________________________________________
Detection_layer (Conv2D)     (None, 13, 13, 30)        30750     
_________________________________________________________________
YOLO_output (Reshape)        (None, 13, 13, 5, 6)      0         
=================================================================
Total params: 3,259,614
Trainable params: 3,237,726
Non-trainable params: 21,888
_________________________________________________________________
Loading pre-trained weights in cornea1_bestLoss.h5
Traceback (most recent call last):
  File "train.py", line 138, in <module>
    _main_(_args)
  File "train.py", line 107, in _main_
    yolo.load_weights(config['train']['pretrained_weights'])
  File "/content/keras_yolo2/keras_yolov2/frontend.py", line 83, in load_weights
    self._model = load_model(weight_path, custom_objects={"yolo_loss": keras.losses.mse , "tf": tf})
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 274, in _deserialize_model
    reshape=False)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 682, in preprocess_weights_for_loading
    weights = convert_nested_model(weights)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 670, in convert_nested_model
    original_backend=original_backend))
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 682, in preprocess_weights_for_loading
    weights = convert_nested_model(weights)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 658, in convert_nested_model
    original_backend=original_backend))
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 801, in preprocess_weights_for_loading
    weights[0] = np.transpose(weights[0], (3, 2, 0, 1))
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 575, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 52, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: axes don't match array`

**Comment by rodrigo2019** [comment]
Hi, I think that I fixed the problem, please update your fork and try again

**Comment by dr-askar** [comment]
Thank you 
i have download the code last week ..
 i will try to update and give you feed back .. thanx

**Comment by dr-askar** [comment]
same problem even after update 

`Using TensorFlow backend.
2019-04-04 06:10:26.777551: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2300000000 Hz
2019-04-04 06:10:26.777826: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x27b51e0 executing computations on platform Host. Devices:
2019-04-04 06:10:26.777878: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-04-04 06:10:26.874273: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-04-04 06:10:26.874892: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x27b4c60 executing computations on platform CUDA. Devices:
2019-04-04 06:10:26.874949: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): Tesla K80, Compute Capability 3.7
2019-04-04 06:10:26.875341: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:04.0
totalMemory: 11.17GiB freeMemory: 11.10GiB
2019-04-04 06:10:26.875380: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-04-04 06:10:27.253379: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-04-04 06:10:27.253481: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-04-04 06:10:27.253495: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-04-04 06:10:27.253811: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10754 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3.7)
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Downloading data from https://github.com/fchollet/deep-learning-models/releases/download/v0.6/mobilenet_1_0_224_tf_no_top.h5
17227776/17225924 [==============================] - 0s 0us/step
Loading pretrained weights: ./backend_weights/mobilenet_backend.h5
Unable to load backend weights. Using a fresh model
(7, 7)
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         (None, 224, 224, 3)       0         
_________________________________________________________________
MobileNet_backend (Model)    (None, 7, 7, 1024)        3228864   
_________________________________________________________________
Detection_layer (Conv2D)     (None, 7, 7, 30)          30750     
_________________________________________________________________
YOLO_output (Reshape)        (None, 7, 7, 5, 6)        0         
=================================================================
Total params: 3,259,614
Trainable params: 3,237,726
Non-trainable params: 21,888
_________________________________________________________________
Traceback (most recent call last):
  File "predict.py", line 145, in <module>
    _main_(_args)
  File "predict.py", line 74, in _main_
    yolo.load_weights(weights_path)
  File "/content/keras_yolo2/keras_yolov2/frontend.py", line 77, in load_weights
    self._model.load_weights(weight_path)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/network.py", line 1166, in load_weights
    f, self.layers, reshape=reshape)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 1045, in load_weights_from_hdf5_group
    reshape=reshape)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 682, in preprocess_weights_for_loading
    weights = convert_nested_model(weights)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 670, in convert_nested_model
    original_backend=original_backend))
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 682, in preprocess_weights_for_loading
    weights = convert_nested_model(weights)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 658, in convert_nested_model
    original_backend=original_backend))
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 801, in preprocess_weights_for_loading
    weights[0] = np.transpose(weights[0], (3, 2, 0, 1))
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 575, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 52, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: axes don't match array`

**Comment by rodrigo2019** [comment]
it's strange, could you share your config file?
because in my environment it's work

**Comment by dr-askar** [comment]
this is my config file
i have very good result when i trained using it 
but i cant reload it to retrain or predict 
`{
    "model" : {
        "backend":              "MobileNet", 
        "input_size_w":         416,
        "input_size_h":         416,
        "gray_mode":            false,
        "anchors":              [5.92000,3.72232, 10.23135,13.57805, 13.86562,23.77973, 19.81026,26.68416, 27.34583,27.71786],
        "max_box_per_image":    10,        
        "labels":               ["as_curve"]
    },

    "parser_annotation_type":    "xml",

    "train": {
        "train_csv_file":       "",
        "train_csv_base_path":  "",
        "train_image_folder":   "/content/raccoon_dataset/cornea/images/",
        "train_annot_folder":   "/content/raccoon_dataset/cornea/ann/",     

        "callback":             null,
        "train_times":          8,
        "pretrained_weights":   "",
        "batch_size":           8,
        "learning_rate":        1e-4,
        "nb_epochs":            150,
        "warmup_epochs":        15,

        "workers":              12,
        "max_queue_size":       40,
        "early_stop":           true,
        "tensorboard_log_dir":  "./logs",

        "object_scale":         6.0 ,
        "no_object_scale":      1.0,
        "coord_scale":          2.0,
        "class_scale":          1.0,

        "saved_weights_name":   "cornea1.h5",
        "debug":                true
    },

    "valid": {
        "iou_threshold":        0.7,
        "score_threshold":      0.5,
        "valid_csv_file":       "",
        "valid_csv_base_path":  "",
        "valid_image_folder":   "",
        "valid_annot_folder":   "",

        "valid_times":          1
    },

    "backup":{
        "create_backup":        false,
        "redirect_model":       true,
        "backup_path":          "../backup",
        "backup_prefix":        "Tiny_yolo_VOC"
    }
}`

and this is the model file 
https://drive.google.com/open?id=1VJbHxiLEcFkNvsjLDip0J6LJlpp8u7Pb

i am using colab from google to train my model

thanx

**Comment by rodrigo2019** [comment]
@dr-askar I didn't try reloading or doing some kind of inference, I will try and give to you a possible solution

**Comment by dr-askar** [comment]
@rodrigo2019 thank you very much
by the way ihave this problem only with MobileNet but i had no problem with retraining using yolo .. tiny yolo or squeeznet .. i didnt try inception 
my that help you 

i have another question how can i made a custom backend 

thanx alot

**Comment by rodrigo2019** [comment]
Are you resolved this issue?
