### ISSUE TITLE
AttributeError: 'ProgbarLogger' object has no attribute 'log_values'

### ISSUE THREAD

**Issue by EphChem** [rodrigo2019/keras-yolo2#9]
Hi,

I downloaded your code and tried to run it without changing anything (I only entered dir of train/valid image and annotation folders in config.json).  When I try to run `python train.py -c config.json`, I get following error:

`Traceback (most recent call last):
  File "train.py", line 138, in <module>
    _main_(_args)
  File "train.py", line 133, in _main_
    score_threshold=config['valid']['score_threshold'])
  File "/home/user/Projects/Object_Detection/YOLO/keras_yolo2-fork_master/keras_yolov2/frontend.py", line 210, in train
    max_queue_size=max_queue_size)
  File "/home/user/miniconda3/envs/py35tf19/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/user/miniconda3/envs/py35tf19/lib/python3.5/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/user/miniconda3/envs/py35tf19/lib/python3.5/site-packages/keras/engine/training_generator.py", line 251, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/user/miniconda3/envs/py35tf19/lib/python3.5/site-packages/keras/callbacks.py", line 79, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/user/miniconda3/envs/py35tf19/lib/python3.5/site-packages/keras/callbacks.py", line 338, in on_epoch_end
    self.progbar.update(self.seen, self.log_values)
AttributeError: 'ProgbarLogger' object has no attribute 'log_values'
`

Tried to debug but still not working.  
Please can you help?
Thanks.

**Comment by rodrigo2019** [comment]
I think your problem is relationed with your keras version
